default_context:
  project_name: 'fastAPI_sandbox'
  project_slug: 'fastAPI_sandbox'
  domain_main: 'fastAPI_sandbox.com'
  domain_staging: 'stag.fastAPI_sandbox.com'
  docker_swarm_stack_name_main: 'fastAPI_sandbox-com'
  docker_swarm_stack_name_staging: 'stag-fastAPI_sandbox-com'
  secret_key: '201a6d2c7b1bf89373b664f33d6824012d694cd8c57ea13dfb566d8269dad89a'
  first_superuser: 'admin@fastAPI_sandbox.com'
  first_superuser_password: '1c7682dfa54fd6ce28f941f67a53d027f0b86975bd1d5d592ae53bad3c800181'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastAPI_sandbox.com", "https://stag.fastAPI_sandbox.com", "https://fastAPI_sandbox.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastAPI_sandbox.com'
  postgres_password: 'ad4098a78ee217c96059a3a910a312727ca1e0d459ab39064c903d233ebcddcb'
  pgadmin_default_user: 'admin@fastAPI_sandbox.com'
  pgadmin_default_user_password: '49b0e9087d01bc37d8e42efaed549283334f4629adfe7b60dd8c4d2b0d2ff548'
  traefik_constraint_tag: 'fastAPI_sandbox.com'
  traefik_constraint_tag_staging: 'stag.fastAPI_sandbox.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:1c7682dfa54fd6ce28f941f67a53d027f0b86975bd1d5d592ae53bad3c800181'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
